version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /usr/src/app/backend/node_modules
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
      - /usr/src/app/frontend/node_modules
    stdin_open: true
    tty: true
